name: CI

on:
  push:
    branches: [main]

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Установка Boost (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libboost-test-dev

      - name: Установка Boost (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install boost

      - name: Конфигурация CMake
        run: cmake -S . -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Сборка
        run: cmake --build build

      - name: Тесты
        run: ctest --test-dir build --output-on-failure
